name: Engine Build

on: push

jobs:
  build:
    name: ${{ matrix.os }} (${{ matrix.config }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [Ubuntu-latest, Windows-latest]
        config: [Debug, Release]
    steps:
      - uses: actions/checkout@v4

      - name: Install Linux Dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install -y libx11-dev

      - name: Configure CMake
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=${{ matrix.config }}

      - name: Build Engine
        run: cmake --build build --config ${{ matrix.config }}
